version: '3'

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
  nino_backend:
    build:
      context: ../
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - 8080:8080